name: "Риг: Предложение рига"
description: "Заполните информацию о риге, который хотите предложить."
labels: ["new rig"]
body:
  - type: input
    id: rig_name
    attributes:
      label: "Название рига"
      placeholder: "Введите название рига"
    validations:
      required: true
  
  - type: input
    id: creator
    attributes:
      label: "Создатель(и) рига и ссылка на него(них)"
      placeholder: "Введите имя автора и ссылку (если есть)"
    validations:
      required: true
  
  - type: input
    id: preview_image
    attributes:
      label: "Картинка для превью рига"
      placeholder: "Добавьте ссылку на изображение"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: "Краткое описание"
      placeholder: "Опишите риг в нескольких предложениях"
    validations:
      required: true
  
  - type: input
    id: tags
    attributes:
      label: "Теги"
      placeholder: "Введите теги через запятую"
    validations:
      required: true
  
  - type: input
    id: download_link
    attributes:
      label: "Ссылка на скачивание"
      placeholder: "Введите ссылку на файл"
    validations:
      required: true